CREATE TABLE IF NOT EXISTS nfl_games (
  game_id TEXT PRIMARY KEY,
  bdl_game_id INTEGER NOT NULL UNIQUE,
  season INTEGER NOT NULL,
  week INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  kickoff_at TEXT,
  status_state TEXT NOT NULL,
  status_text TEXT,
  postseason INTEGER NOT NULL DEFAULT 0,
  venue TEXT,
  summary TEXT,
  home_team_id INTEGER NOT NULL,
  home_team_abbr TEXT NOT NULL,
  home_team_name TEXT,
  away_team_id INTEGER NOT NULL,
  away_team_abbr TEXT NOT NULL,
  away_team_name TEXT,
  home_score INTEGER,
  away_score INTEGER,
  source TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  ingested_at TEXT NOT NULL,
  payload_hash TEXT NOT NULL,
  raw_r2_key TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  build TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_nfl_games_season_week ON nfl_games(season, season_type, week);
CREATE INDEX IF NOT EXISTS idx_nfl_games_status ON nfl_games(season, season_type, status_state);
CREATE TABLE IF NOT EXISTS nfl_team_game_stats (
  game_id TEXT NOT NULL,
  bdl_game_id INTEGER NOT NULL,
  season INTEGER NOT NULL,
  week INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  team_id INTEGER NOT NULL,
  team_abbr TEXT NOT NULL,
  team_name TEXT,
  opponent_team_id INTEGER,
  opponent_abbr TEXT,
  home_away TEXT,
  first_downs INTEGER,
  third_down_conversions INTEGER,
  third_down_attempts INTEGER,
  fourth_down_conversions INTEGER,
  fourth_down_attempts INTEGER,
  total_offensive_plays INTEGER,
  total_yards INTEGER,
  yards_per_play REAL,
  total_drives INTEGER,
  net_passing_yards INTEGER,
  passing_completions INTEGER,
  passing_attempts INTEGER,
  yards_per_pass REAL,
  sacks INTEGER,
  sack_yards_lost INTEGER,
  rushing_yards INTEGER,
  rushing_attempts INTEGER,
  yards_per_rush_attempt REAL,
  red_zone_scores INTEGER,
  red_zone_attempts INTEGER,
  penalties INTEGER,
  penalty_yards INTEGER,
  turnovers INTEGER,
  fumbles_lost INTEGER,
  interceptions_thrown INTEGER,
  defensive_touchdowns INTEGER,
  possession_time_seconds INTEGER,
  source TEXT NOT NULL,
  observed_at TEXT NOT NULL,
  ingested_at TEXT NOT NULL,
  payload_hash TEXT NOT NULL,
  raw_r2_key TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  build TEXT NOT NULL,
  PRIMARY KEY (game_id, team_id)
);
CREATE INDEX IF NOT EXISTS idx_nfl_team_stats_season_team_week ON nfl_team_game_stats(season, team_id, week);
CREATE TABLE IF NOT EXISTS nfl_ssot_runs (
  run_id TEXT PRIMARY KEY,
  phase TEXT NOT NULL,
  season INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  status TEXT NOT NULL,
  cursor TEXT,
  processed_pages INTEGER NOT NULL DEFAULT 0,
  fetched_rows INTEGER NOT NULL DEFAULT 0,
  stored_rows INTEGER NOT NULL DEFAULT 0,
  error_count INTEGER NOT NULL DEFAULT 0,
  started_at TEXT NOT NULL,
  updated_at TEXT NOT NULL,
  completed_at TEXT,
  checkpoint_json TEXT,
  build TEXT NOT NULL
);
CREATE TABLE IF NOT EXISTS nfl_ssot_receipts (
  receipt_id TEXT PRIMARY KEY,
  run_id TEXT NOT NULL,
  phase TEXT NOT NULL,
  season INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  page_cursor TEXT,
  next_cursor TEXT,
  source_row_count INTEGER NOT NULL,
  stored_row_count INTEGER NOT NULL,
  payload_hash TEXT NOT NULL,
  raw_r2_key TEXT NOT NULL,
  created_at TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  build TEXT NOT NULL
);
CREATE INDEX IF NOT EXISTS idx_nfl_ssot_receipts_run ON nfl_ssot_receipts(run_id, created_at);
CREATE TABLE IF NOT EXISTS nfl_ssot_certifications (
  cert_key TEXT PRIMARY KEY,
  season INTEGER NOT NULL,
  season_type INTEGER NOT NULL,
  phase TEXT NOT NULL,
  complete INTEGER NOT NULL,
  certified INTEGER NOT NULL,
  expected_rows INTEGER NOT NULL,
  found_rows INTEGER NOT NULL,
  missing_rows INTEGER NOT NULL,
  invalid_rows INTEGER NOT NULL,
  details_json TEXT,
  assessed_at TEXT NOT NULL,
  schema_version TEXT NOT NULL,
  build TEXT NOT NULL
);
